version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: bch-node_web_1
      APP_PORT: 8080

  web:
    image: nginx:alpine
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/status:/usr/share/nginx/html:ro

  node:
    image: zquestz/bitcoin-cash-node:latest
    restart: on-failure
    stop_grace_period: 1m

    ports:
      - "9333:8333"
      - "9332:8332"

    volumes:
      - ${APP_DATA_DIR}/data:/data

    environment:
      BITCOIN_RPC_USER: umbrel
      BITCOIN_RPC_PASSWORD: ${APP_PASSWORD}
